server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

spring:
  cloud:
    gateway:
      routes:
        # Ruta exacta para /categoria
        - id: categoria
          uri: http://localhost:65234
          predicates:
            - Path=/categoria
          filters:
            - SetPath=/api/categorias

        # Ruta exacta para /producto  
        - id: producto
          uri: http://localhost:65234
          predicates:
            - Path=/producto
          filters:
            - SetPath=/api/productos

        # Rutas directas
        - id: api-routes
          uri: http://localhost:65234
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
