server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        # Ruta directa a IP:Puerto (sin Eureka)
        - id: categorias-direct
          uri: http://localhost:65234
          predicates:
            - Path=/categoria
          filters:
            - SetPath=/api/categorias

        - id: productos-direct
          uri: http://localhost:65234
          predicates:
            - Path=/producto
          filters:
            - SetPath=/api/productos

        # Rutas API directas
        - id: api-categorias-direct
          uri: http://localhost:65234
          predicates:
            - Path=/api/categorias
            
        - id: api-productos-direct
          uri: http://localhost:65234
          predicates:
            - Path=/api/productos/**

        # Actuator
        - id: actuator-direct
          uri: http://localhost:65234
          predicates:
            - Path=/actuator/**

        # Swagger
        - id: swagger-direct
          uri: http://localhost:65234
          predicates:
            - Path=/doc/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG

# Deshabilitar Eureka para el gateway temporalmente
eureka:
  client:
    enabled: false
