server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta simple para /categoria -> /api/categorias
        - id: categoria-route
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/categorias

        # Ruta simple para /categoria (sin barra final)
        - id: categoria-root
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria
          filters:
            - PrefixPath=/api/categorias

        # Ruta simple para /producto -> /api/productos  
        - id: producto-route
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/producto/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/productos

        # Ruta simple para /producto (sin barra final)
        - id: producto-root
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/producto
          filters:
            - PrefixPath=/api/productos

        # Rutas directas sin modificación
        - id: catalogo-api-direct
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/api/**

        # Autenticación
        - id: auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
