server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        # Ruta para /categoria -> /api/categorias (puerto fijo)
        - id: categorias-route
          uri: http://localhost:8081
          predicates:
            - Path=/categoria
          filters:
            - SetPath=/api/categorias

        # Ruta para /producto -> /api/productos (puerto fijo)
        - id: productos-route
          uri: http://localhost:8081
          predicates:
            - Path=/producto
          filters:
            - SetPath=/api/productos

        # Rutas API directas
        - id: api-categorias
          uri: http://localhost:8081
          predicates:
            - Path=/api/categorias

        - id: api-productos
          uri: http://localhost:8081
          predicates:
            - Path=/api/productos/**

        # Actuator y Swagger
        - id: actuator
          uri: http://localhost:8081
          predicates:
            - Path=/actuator/**

        - id: swagger
          uri: http://localhost:8081
          predicates:
            - Path=/doc/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

# Deshabilitar Eureka temporalmente
eureka:
  client:
    enabled: false
