server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para /categoria -> /api/categorias (compatibilidad)
        - id: categoria-legacy
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria, /categoria/**
          filters:
            - name: RewritePath
              args:
                regexp: /categoria/?(?<segment>.*)
                replacement: /api/categorias/${segment}

        # Ruta para /producto -> /api/productos (compatibilidad)  
        - id: producto-legacy
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/producto, /producto/**
          filters:
            - name: RewritePath
              args:
                regexp: /producto/?(?<segment>.*)
                replacement: /api/productos/${segment}

        # Rutas modernas /api/*
        - id: catalogo-api
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/api/categorias/**, /api/productos/**

        # Ruta para autenticación
        - id: auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        # Actuator y Swagger
        - id: catalogo-actuator
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/actuator/**, /doc/**, /v3/api-docs/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route: DEBUG
